Create another deployment named redis-slave for Redis slave.

a.) Replicas count should be 2.

b.) Container name should be slave-redis-datacenter and it should use gcr.io/google_samples/gb-redisslave:v3 image.

c.) Requests resources as CPU should be 100m and Memory should be 100Mi.

d.) Define an environment variable named GET_HOSTS_FROM and its value should be dns.

e.) Container port should be Redis default port i.e 6379.


---
#BACK-END TIER
#
#Create a deployment named redis-master for Redis master.
#
#a.) Replicas count should be 1.
#
#b.) Container name should be master-redis-datacenter and it should use image redis.
#
#c.) Request resources as CPU should be 100m and Memory should be 100Mi.
#
#d.) Container port should be redis default port i.e 6379

---
apiVersion: app/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis-slave
      tier: back-end
  template:
    metadata:
      labels:
        app: redis-slave
        tier: back-end
    spec:
      containers:
        - name: slave-redis-xfusion
          image: gcr.io/google_samples/gb-redisslave:v3
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
          ports:
           - containerPort: 6379